### ISSUE TITLE
Callback function 

### ISSUE THREAD

**Issue by aldwnesx** [rydmike/flex_color_picker#1]
I am trying to store the color selected into sharedpreference, but it looks like the callback function isn't working:

```
  color: screenPickerColor,
                onColorChanged: (Color color) {
                  print("new color ");
                  print(color);
                },
```

**Comment by rydmike** [comment]
Hi @aldwnesx,

It is a bit difficult to see from your short sample what might be wrong, but from what is shown I suspect your implementation/usage might be causing the issue.

I took the basic example included with the package and added print statements to the `onColorChanged` callback there for both the Card and Dialog example.

In a Card here:
![image](https://user-images.githubusercontent.com/39990307/103456338-c88c3200-4cfd-11eb-8ac1-8fd56819d60a.png)

In a Dialog here:
![image](https://user-images.githubusercontent.com/39990307/103456344-d6da4e00-4cfd-11eb-8f3f-6de80d1a82c1.png)

You can find the complete code for this modified example with the print statements baked in here:
https://gist.github.com/rydmike/65d9219a5d8be61bc9b31077c531ebe3

When I use this example, the `onColorChanged` callback appears to be working as it should in both cases

![colorpicker_issue1](https://user-images.githubusercontent.com/39990307/103456370-0be6a080-4cfe-11eb-9899-e7ff1309b784.gif)

If you compare your code with the example code, can you find any major differences between it and your implementation from a usage principle point of view? If you do, then that might help you solve the issue. 

If it does not help, then if you provide a link to short a Gist sample or complete GitHub repo with your code, I might be able to assist further.

Mike

**Comment by aldwnesx** [comment]
Hello, thanks so much for your reply.

The problem seems to be gone after I restarted my PC, so weird!

Thank you for the great wokrk

**Comment by rydmike** [comment]
No problem, happy to help and that you got it to work :)
