### ISSUE TITLE
[feedback] option for adding a quick-access list of colors 

### ISSUE THREAD

**Issue by osaxma** [rydmike/flex_color_picker#10]
Hi Mike, 

Just a feedback, I think adding an option for something like: `quickAccessColorList` and `quickAccessSubheading` could be a nice add-on. I didn't face any issues to implement it myself but I thought I'd share the idea with you in case you find fit for this package. I personally found it useful when adding a list of recent colors, or a list of favorite colors as shown below:

<img width="489" alt="Screen Shot 2021-02-26 at 5 57 05 PM" src="https://user-images.githubusercontent.com/46427323/109315866-0d46cc00-785c-11eb-827a-30cb54131f1e.png">

Edit:
By the way, not visible in the screenshot, the `Recent Colors` are shown in every tab.

**Comment by rydmike** [comment]
That's a really nice feature, I like it! Not even difficult to do, I will add as feature too 😃

**Comment by rydmike** [comment]
This feature is now available starting from the pre-release ^2.0.0-nullsafety.1
https://pub.dev/packages/flex_color_picker/versions/2.0.0-nullsafety.2/changelog

You can try and play with the features in the latest web demo as well: https://rydmike.com/flexcolorpicker
The web demo source code is available in the latest package release as well.

These features are still new and still in pre-release status. I expect to migrate 2.0.0 over to stable channel soon after the dust settles from Flutter Engage. 

Let me know if you notice anything that needs further tweaking.

Closing this feature request as it is now implemented. 😃
