### ISSUE TITLE
ColorCodeField is requesting focus causing the keyboard to show up along with dialog

### ISSUE THREAD

**Issue by osaxma** [rydmike/flex_color_picker#11]
Hi Mike,

Using `2.0.0-nullsafety.2` with `Flutter 2.0.0` in iOS, calling `showPickerDialog` cause the keyboard shows up right away because `ColorCodeField` is requesting the focus. This only happens when `ColorPickerType.wheel: true` in `pickersEnabled`. 

Similarly, when the wheel is enabled, it'll be the first tab to be shown even though it's the last one (it could also be caused by the focus request).

by the way, thanks for other fixes. I still didn't get a chance to try them out.

**Comment by rydmike** [comment]
Thanks for letting me know. I will take a look later today. Have to admit I did not test this completely on all platforms with Flutter 2 and null-safety enbanabled yet, hence the 'pre' label.

Publishing it was a bit rushed to get it out there in hands of other testers like you and to at least have it available for Fluttee v2 launch. 

Appreciate the quick feedback.

**Comment by rydmike** [comment]
Bug fixed via https://github.com/rydmike/flex_color_picker/projects/1#card-56740562

Published here: https://pub.dev/packages/flex_color_picker/versions/2.0.0-nullsafety.3

You can play with the latest 2.0.0 pre-release web demo here: https://rydmike.com/flexcolorpicker
The web demo app source is bundled with the package, it can work as guide for now while docs are still pending updates. The updated live web demo app also has interactive API tooltip guides, they may also be handy.

As mentioned the docs are not yet updated to 2.0.0, that will have to be done before I release 2.0.0 stable version. Plus I would like to add more tests and a CI/CD pipe to this package as well before I release it as stable 2.0.0. And perhaps that opacity slider feature as well.

This release has some new features, full change log as always here: https://pub.dev/packages/flex_color_picker/versions/2.0.0-nullsafety.3/changelog
