### ISSUE TITLE
Can't found Transparent selection

### ISSUE THREAD

**Issue by justkawal** [rydmike/flex_color_picker#2]
Hey, Firstly thanks for this awesome library with wide variety of features.

I wanted to go for transparent selection but I was unable to find it ?

**Comment by rydmike** [comment]
Very understandable as does not have transparent colors yet. 😄 

I was planning on including it in a totally new different "advanced" picker option/section in a future update to it. But even without that being delivered, I could probably add an option to enable an optional slider and opacity entry on the wheel picker page, for those that need it. I will look into it as it is certainly a missing feature that it should have imo too.

**Comment by rydmike** [comment]
Just as info and update. Working on the transparency addition. It will be in the next release with null-safety.
Probably won't back port the feature to the null-safe version. Depends on what happens 3/3 at Flutter Engage though.

**Comment by justkawal** [comment]
Would be waiting for the update. 🙌

**Comment by rydmike** [comment]
Finally added opacity support to FlexColorPikcer, it is still just available as pre-release.

https://pub.dev/packages/flex_color_picker/versions/2.0.0-nullsafety.4
![image](https://user-images.githubusercontent.com/39990307/111939343-b0de7180-8ad4-11eb-9b35-7fcb98a9f4c2.png)

Available as a web demo here, the demo has API tooltips (can be turned OFF if they get annoying): https://rydmike.com/flexcolorpicker/#/

>**NOTE:**   
> This is **FlexColorPicker 2.0.0 dev and pre-release** with sound null safety. It contains many new features compared to previous stable 1.1.5 none null safe version.
> The package documentation has not yet been updated to cover the new features that are being introduced in final 2.0.0 version together with null-safety. The changelog covers the major changes. The API-documentation is up to date as well. The bundled and live [**web demo app**](https://rydmike.com/flexcolorpicker) demonstrates all the new features, and you can change most API settings. The demo also shows each API name and current value in a tooltip for each control that modifies API values in the demo.
> No more new features will be added to 2.0.0 before the pending stable release. This release is a stabilization and fine-tuning phase. The remaining minimum requirements for releasing stable version 2 is an update of this package documentation to cover all new features. Later releases will provide additional refinements, further testing and CI/CD pipe.


cc: @osaxma might interest you too.

**Comment by justkawal** [comment]
@rydmike 
Thanks
