### ISSUE TITLE
null-safety support

### ISSUE THREAD

**Issue by muhlba91** [rydmike/flex_color_picker#4]
Flutter's dev channel introduces null-safety. Are there plans to migrate the plugin to support null-safety? Potentially with a prerelease for people using the dev channel already?

**Comment by rydmike** [comment]
Hi @muhlba91, thanks for the question. 

Yes I will definitely be migrating and adding a null safe version, probably during next week. Using this picker a lot myself in projects too and some are about to be migrated to null-safety as soon as all deps support it, this being one of them, lol.
Also I want to get this package migrated before 3/3 when Google probably launches null safety in the stable channel.

It is a simple enough migration, I have just been contemplating adding some new features to it before the migration. But I think I might added them later to the null safe version instead 3/3 is getting close already.

I also plan to add more tests to this package, automated tests runs on commits, test coverage report and test build CI/CD pipeline too, kind of like I did for the FlexColorScheme package (https://github.com/rydmike/flex_color_scheme/blob/v2-null-safe/CHANGELOG.md)

I'll keep this question and issue open until there is a null-safe version released.

**Comment by rydmike** [comment]
@muhlba91 for your info, the first version of **FlexColorPicker** with null-safety has been released.
Goes without saying it is still a bit experimental, but passed my tests and I built a new Web demo that is based on this version as well.

Null safe version: https://pub.dev/packages/flex_color_picker/versions/2.0.0-nullsafety.0
Updated web demo: https://rydmike.com/democolorpicker

If you find some issues with the null-safe version, please open new issues for them.

Closing this issue. 

BR
Mike
