### ISSUE TITLE
High wheelWidth cause wrong cursor position in the ColorPicker 

### ISSUE THREAD

**Issue by buffedNerd** [rydmike/flex_color_picker#44]
When the wheelWidth is high the cursor inside the wheel get a few problems.

The cursor can get outside of the Square and under the wheel itself. Also is the position only in the middle the same like the mouse position, at the edges it get an offset.

I tested this on:
- Linux
- Android
- Your Web Example (https://rydmike.com/flexcolorpicker/#/)

It looks like the position is calculated without the wheel.

**Comment by rydmike** [comment]
Thanks @buffedNerd, agreed, that is a bug, fix in v2.3.2 coming.

**Comment by rydmike** [comment]
Fixed via https://github.com/rydmike/flex_color_picker/pull/46.
Release on pub in a few minutes as version 2.4.0.
