### ISSUE TITLE
Square padding

### ISSUE THREAD

**Issue by alejandrogiubel** [rydmike/flex_color_picker#47]
Hi great plugin!. Any way to add a padding to square inside the wheel?

**Comment by rydmike** [comment]
Thanks @alejandrogiubel !😄 
Probably not in current version. Could you perhaps make screenshot with some drawing/mockup indicating where you would like to have some padding capability? What should it look like? 

Perhaps it can be added. The wheel is a custom painter, so its certainly possible to draw whatever, just not with a padding widget per say.

----

BW - finally got V5 of this this released https://pub.dev/packages/flex_color_scheme

**Comment by rydmike** [comment]
Nice mockup and I think I got it. Yes I agree that is a nice layout feature to be able to adjust.
So like this then? 😄 

![fcp-v2-5-0_1](https://user-images.githubusercontent.com/39990307/164530879-b10ca496-a350-4331-baf2-62672468822f.gif)

Notice btw that thumb keeps its relative position when you adjust the shade square padding and the wheel width.

Added border radius adjustment of the shade square too, it was hard coded to 4 dp before.

Releasing version 2.5.0 in a few minutes with two new props as below A new web demo build with these features included is built and published automatically too when I release it.

```dart
  /// Padding between shade square inside the hue wheel and inner
  /// side of the wheel.
  ///
  /// Keep it reasonable in relation to wheelDiameter and wheelWidth, values
  /// from 0 to 20 are recommended.
  ///
  /// Defaults to 0 dp.
  final double wheelSquarePadding;

  /// Border radius of the shade square inside the hue wheel.
  ///
  /// Keep it reasonable, the thumb center always goes out to the square box
  /// corner, regardless of this border radius. It is only for visual design,
  /// the edge color shades are in the sharp corner, even if not shown.
  ///
  /// Recommended values 0 to 16.
  ///
  /// Defaults to 4 dp.
  final double wheelSquareBorderRadius;
```

**Comment by 70nybl4nc0** [comment]
I think that setting the `wheelSquareBorderRadius` will cause to lose some important corner colors, like pure white or black.

**Comment by alejandrogiubel** [comment]
@rydmike 
:flushed: That was unbelievably fast. Thanks for the quick support. That's exactly what we needed :grin:

**Comment by rydmike** [comment]
You are welcom!

BTW, the rounding does not affect the color. 

The thumb still moves all the way to the sharp corner box, even when visually rounded. The color's shade comes from the thumbs relative position in the box, not from the shade actually visually shown behind it, so you get correct color result even if you round the corners a bit visually or as much as you want, they were always rounded to 4dp before.

For example this still becomes white, since you are in the full white shade corner
![image](https://user-images.githubusercontent.com/39990307/164535630-ef6bbe4f-6b06-4581-8123-300dbb5a5c1f.png)

**Comment by rydmike** [comment]
Updated WEB demo just updated itself too via GitHub actions release: https://rydmike.com/flexcolorpicker

**Comment by adityasethipsi** [comment]
https://user-images.githubusercontent.com/39990307/164530879-b10ca496-a350-4331-baf2-62672468822f.gif 

When user taps in the blank space between wheel and square, it changes the wheel color selector (rounder white circle) position. This is making the inner rounded white color dragging difficult when it's position is on the corner of square. This tap functionality should only work when user click on wheel itself or drag the circle of wheel.

**Comment by adityasethipsi** [comment]
Can we reopen this and try to resolve this
