### ISSUE TITLE
FlexColorPicker Demo Slider issue

### ISSUE THREAD

**Issue by iqfareez** [rydmike/flex_color_picker#64]
This is just minor visual issue on the demo apo (I think)

https://user-images.githubusercontent.com/60868965/212215371-db2c9c81-88d0-4976-8c42-3c537f244fba.mp4

**Comment by rydmike** [comment]
Thanks @iqfareez, confirmed it is bug in the web demo app and only in it.

The Slider and it value should update. The Picker component is updating correctly but slider does not move. That the slider below it moves is correct, its value actually remains same, but it max border radius slider range increases as the picker item sizes increase, so it moves as max moves further away.

But yeah the picker item size Slider should update too. Pushing a fix and building new version of web app now...

**Comment by rydmike** [comment]
Package that includes fixed web demo published.
The actual Web demo update is still building via GitHub action and will be updated automically on its GitHub pages hosting as well. You should see it live in maybe 15 min.

**Comment by iqfareez** [comment]
Great. Thank you ❤️
