### ISSUE TITLE
Inner circle does not move

### ISSUE THREAD

**Issue by GAayushi** [rydmike/flex_color_picker#67]
I'm facing this problem, that while using colour wheel, if I try to move the inner square selector circle, sometimes it doesn't move, instead the outer circle move. This problem occurs mostly when inner circle is at any corner or on the outer edges of the square. We need to click on the square first then the inner circle moves. Any fixes for this?

**Comment by rydmike** [comment]
Thanks @GAayushi for this report, and I agree, I have noticed this too, it is an issue. Looks like I need to take another look at the hit testing and improve it a bit.

**Comment by rydmike** [comment]
Hi @GAayushi, thanks for raising this issue. Hope you have had a chance to try the FIX. At least in my tests, clicking on circle or box is now reliable. This issue had been bothering me too, not sure why I had not looked into before. Anyway let me know what you think, hope it works well for you too.

**Comment by edwardocano** [comment]
Hello! I am having this same issue , in iOS when i use the square it is now reliable when the selector is in the corners i need to try several times to move it.

**Comment by rydmike** [comment]
Hi @edwardocano, this is an old closed issue. If you are still experiencing an issue with it, please open a new issue that demonstrates the clearly issue.

The issue referred to here with accidental move of the outer ring has been fixed as they now have different region detector.

Concerning the selector in the square, you can only move the selector, if the tap happens inside the square color gardient box. Tapping on the selector on a part that is outside the square, does indeed not move it. This is expected designed behavior with current implementation.

This recording demonstrates this behavior:

https://github.com/rydmike/flex_color_picker/assets/39990307/947fd792-83c4-48d4-89c7-56eed93e2e0b

You can also move the selector by tapping down anywhere in the square box, so inside the square, but on on the selector work works well, or just outside it a bit too but on the square. By doing so it is not difficult to move it.

It could be changed to not need to be this precisely in the square somewhere, and also count when it is on the round selector in the sqaure. However, one of the challenges with that is that the ColorPicker allows designs where the square and wheel touch, and the selector on the wheel and square can overlap, thus creating a conflict of which one should win. To avoid this, initial down-touch, only count from the square, for square selector or the wheel, for the wheel selector.
