### ISSUE TITLE
Support for multiple custom color pickers / palettes

### ISSUE THREAD

**Issue by lukemmtt** [rydmike/flex_color_picker#70]
I'm incorporating this package into my app, and I noticed that it only seems to support a single custom color picker. As part of my app's UX, I'd like to support the ability for users to select from various pre-set themed color palettes.

First I wanted to confirm that this isn't possible in the existing implementation, and if that's the case I might take it upon myself to fork and implement it, and if it is deemed to be something that might be of interest to others, I can make a PR as well.

Demo video of my app is provided here for reference to understand the use case. In this demo I have one custom color palette ("Pastels") and the "Primary" palette (renamed "Bold").

Thanks for any input!

https://github.com/rydmike/flex_color_picker/assets/1598289/8d337881-4ef7-4cdc-bd32-03a38d0065b1

**Comment by rydmike** [comment]
Correct, there is currently only support for one picker with custom colors in it.

**Comment by rydmike** [comment]
I'm planning to add support for one more `customSecondary` palette in version 3.4.0. Not going to make an arbitrary amount possible in version 3, but may consider more custom palettes in a later major breaking rewrite for version 4.

**Comment by rydmike** [comment]
Support for a 2nd custom palette added to version 3.4.0.

**Comment by rydmike** [comment]
New feature for this added in just release version 3.4.0 https://pub.dev/packages/flex_color_picker/changelog.

Closing this as resolved.

**Comment by lukemmtt** [comment]
Thank you @rydmike!
