### ISSUE TITLE
Missing parameter `surfaceTintColor` in material3

### ISSUE THREAD

**Issue by jctaoo** [rydmike/flex_color_picker#77]
There is a parameter `surfaceTintColor` which controls color of alert could add to `showPickerDialog`

**Comment by rydmike** [comment]
Good point. Added as well as `shadowColor` coming soon in version 3.4.0.

**Comment by rydmike** [comment]
New feature for this added in just release version 3.4.0 https://pub.dev/packages/flex_color_picker/changelog.

Closing this as resolved.
