### ISSUE TITLE
Opacity control exception

### ISSUE THREAD

**Issue by rihansr** [rydmike/flex_color_picker#82]
...
enableOpacity: true
...

Unable to load asset: "packages/flex_color_picker/assets/opacity.png".
Exception: Asset not found

**Comment by rydmike** [comment]
I was unable to replicate this with the web demo in the repo, building it on Android, iOS, macOS and Web targets. The implied asset loading issue, used by the opacity slider, worked fine on all tested targets.

Can you please provide a reproduction sample? With some info about what version of Flutter and what devices and build modes you see this in?

**Comment by rydmike** [comment]
Added tag **waiting for reply**. Will close in 2 weeks if additional reproduction info has not bee provided.

**Comment by rydmike** [comment]
Closed due to no response. We can open this again if there is more info, like a reproduction sample.
